APPLICATION = sensors

BOARD ?= lora-e5-dev

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += xtimer

# Add the required modules here

RIOTBASE ?= $(CURDIR)/../../RIOT

include $(RIOTBASE)/Makefile.include
